# Generated by Django 5.0.2 on 2024-02-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_data', '0002_refundcancellationpolicy_termsandcondition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefundCancellationPolicy',
            new_name='RefundCancellationPolicyTerms',
        ),
    ]
