# Generated by Django 5.0.2 on 2024-02-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_data', '0003_rename_refundcancellationpolicy_refundcancellationpolicyterms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefundCancellationPolicyTerms',
            new_name='RefundCancellationPolicy',
        ),
    ]
