# Generated by Django 5.0.2 on 2024-02-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_data', '0005_rename_title_termsandcondition_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termsandcondition',
            old_name='section',
            new_name='title',
        ),
    ]
