# Generated by Django 5.0.2 on 2024-04-14 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0028_remove_product_sku_code_sizechart_sku_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bestseller_product', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='SpotlightProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotlight_product', to='products.product')),
            ],
        ),
    ]
