# Generated by Django 5.0.2 on 2024-04-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verify',
            field=models.BooleanField(default=False, help_text='Designates whether this user has Verified his account.', verbose_name='Verified'),
        ),
    ]
