# Generated by Django 4.2.14 on 2024-07-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_gst_no_alter_user_pan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
