# Generated by Django 5.0.2 on 2024-02-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='finish',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
