# Generated by Django 5.0.2 on 2024-02-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_finish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
            ],
        ),
        migrations.AlterField(
            model_name='roleprice',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.role'),
        ),
    ]
