# Generated by Django 5.0.2 on 2024-02-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleprice',
            name='price',
        ),
        migrations.AddField(
            model_name='roleprice',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=20),
        ),
    ]
