# Generated by Django 5.0.2 on 2024-02-16 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_role_alter_roleprice_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.maincategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='finish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.finish'),
        ),
    ]
