# Generated by Django 5.0.2 on 2024-02-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_finish_alter_product_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown_number', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=30)),
                ('rack_number', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
        ),
    ]
