# Generated by Django 5.0.2 on 2024-02-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_roleprice_gst_percent_roleprice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleprice',
            name='price',
        ),
        migrations.AddField(
            model_name='roleprice',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=20, null=True),
        ),
    ]
