# Generated by Django 5.0.2 on 2024-02-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_sku_code_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_multi_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ManyToManyField(to='products.multiimages'),
        ),
    ]
