# Generated by Django 5.0.2 on 2024-02-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_roleprice_price_roleprice_gst_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleprice',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=20, null=True),
        ),
    ]
