# Generated by Django 5.0.2 on 2024-02-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_multiimages_remove_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleprice',
            name='product',
        ),
        migrations.AddField(
            model_name='roleprice',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sizechart'),
        ),
    ]
