# Generated by Django 5.0.2 on 2024-02-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_roleprice_gst_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategory',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='sizechart',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='disable',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='status',
            field=models.CharField(choices=[('Activate', 'Activate'), ('Inactivate', 'Inactivate')], default='Activate', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Activate', 'Activate'), ('Inactivate', 'Inactivate')], default='Activate', max_length=10),
        ),
        migrations.AddField(
            model_name='productimage',
            name='status',
            field=models.CharField(choices=[('Activate', 'Activate'), ('Inactivate', 'Inactivate')], default='Activate', max_length=10),
        ),
        migrations.AddField(
            model_name='sizechart',
            name='status',
            field=models.CharField(choices=[('Activate', 'Activate'), ('Inactivate', 'Inactivate')], default='Activate', max_length=10),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('Activate', 'Activate'), ('Inactivate', 'Inactivate')], default='Activate', max_length=10),
        ),
    ]
