# Generated by Django 5.0.2 on 2024-02-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_roleprice_product_roleprice_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sizechart',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
