# Generated by Django 5.0.2 on 2024-02-24 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_maincategory_disable_remove_product_disable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_quantity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
