# Generated by Django 5.0.2 on 2024-02-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productimage_disable_sizechart_disable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizechart',
            name='finish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.finish'),
        ),
    ]
