# Generated by Django 5.0.2 on 2024-02-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_sizechart_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleprice',
            name='price_with_gst',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='roleprice',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
