# Generated by Django 5.0.2 on 2024-02-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_maincategory_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Activate', 'Activate'), ('Inactivate', 'Inactivate')], default='Activate', max_length=10),
        ),
    ]
