# Generated by Django 5.0.2 on 2024-02-26 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='location',
            name='size',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sizechart',
            name='minimum_quantity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sizechart',
            name='stock_quantity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sizechart',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
