# Generated by Django 5.0.2 on 2024-02-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_roleprice_price_with_gst_alter_roleprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='roleprice',
            name='price_with_gst',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
