# Generated by Django 5.0.2 on 2024-02-26 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_minimum_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sizechart'),
        ),
    ]
