# Generated by Django 5.0.2 on 2024-02-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_location_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='size',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
