# Generated by Django 5.0.2 on 2024-02-21 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
