# Generated by Django 5.0.2 on 2024-02-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productdetails_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='ProductDetail',
        ),
    ]
