# Generated by Django 4.2.10 on 2024-02-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_description'),
        ('products', '0015_alter_location_size'),
    ]

    operations = [
    ]
