# Generated by Django 5.0.2 on 2024-03-03 10:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_paymenttransaction_muid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizechart',
            name='minimum_quantity',
        ),
        migrations.RemoveField(
            model_name='sizechart',
            name='stock_quantity',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_quantity', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('size_chart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_quantity', to='products.sizechart')),
            ],
        ),
    ]
