# Generated by Django 4.2.10 on 2024-02-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_merge_20240226_1109'),
        ('products', '0017_alter_paymenttransaction_muid_and_more'),
    ]

    operations = [
    ]
