# Generated by Django 5.0.2 on 2024-03-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_merge_20240228_1749'),
        ('products', '0018_remove_sizechart_minimum_quantity_and_more'),
    ]

    operations = [
    ]
