# Generated by Django 5.0.2 on 2024-03-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_merge_20240303_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='product',
        ),
    ]
