# Generated by Django 5.0.2 on 2024-03-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_location_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleprice',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
