# Generated by Django 5.0.2 on 2024-03-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_roleprice_minimum_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku_code',
        ),
    ]
