# Generated by Django 5.0.2 on 2024-03-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_product_sku_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='minimum_quantity',
        ),
        migrations.AddField(
            model_name='sizechart',
            name='minimum_stock_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
