# Generated by Django 4.2.10 on 2024-03-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_stock_minimum_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizechart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='sku_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
