# Generated by Django 5.0.2 on 2024-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_paymenttransaction_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
