# Generated by Django 5.0.2 on 2024-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_paymenttransaction_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku_code',
        ),
        migrations.AddField(
            model_name='sizechart',
            name='sku_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
