# Generated by Django 5.0.2 on 2024-05-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_product_sku_code_sizechart_sku_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoice'),
        ),
    ]
