# Generated by Django 5.0.2 on 2024-05-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_paymenttransaction_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
