# Generated by Django 5.0.2 on 2024-05-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_paymenttransaction_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='signature',
            new_name='razorpay_signature',
        ),
    ]
