# Generated by Django 5.0.2 on 2024-07-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_rename_signature_paymenttransaction_razorpay_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='delivery_date',
            field=models.DateTimeField(null=True, verbose_name='Delivery Time'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Deliverd'),
        ),
    ]
